sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

language: go
go:
  - "1.12"

before_install:
  - docker --version
  - go mod download

install: skip

cache:
  - directories:
      - $GOPATH/pkg

env:
  - GO111MODULE=on

jobs:
  include:
    - name: Lint
      stage: test
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
        - export PATH=$PATH:$(go env GOPATH)/bin
        - golangci-lint --version
      script: ./scripts/runLint.sh

    - name: Unit Tests
      script: ./scripts/runUnitTests.sh

    - name: Acceptance
      script: ./scripts/runIntegrationAcceptance.sh

    - name: Performance
      script: ./scripts/runIntegrationPerformance.sh

    - name: Fault Injection
      script: ./scripts/runIntegrationFaultInjection.sh

    - name: Meteor
      script: ./scripts/runIntegrationMeteor.sh
